// Code generated for Alex Sokolov service
// © Alexey Sokolov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	user_v1 "github.com/alexis871aa/microservices-rocket-factory/shared/pkg/proto/user/v1"
)

// UserServiceClient is an autogenerated mock type for the UserServiceClient type
type UserServiceClient struct {
	mock.Mock
}

type UserServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceClient) EXPECT() *UserServiceClient_Expecter {
	return &UserServiceClient_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) GetUser(ctx context.Context, in *user_v1.GetUserRequest, opts ...grpc.CallOption) (*user_v1.GetUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *user_v1.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user_v1.GetUserRequest, ...grpc.CallOption) (*user_v1.GetUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user_v1.GetUserRequest, ...grpc.CallOption) *user_v1.GetUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_v1.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user_v1.GetUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserServiceClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user_v1.GetUserRequest
//   - opts ...grpc.CallOption
func (_e *UserServiceClient_Expecter) GetUser(ctx interface{}, in interface{}, opts ...interface{}) *UserServiceClient_GetUser_Call {
	return &UserServiceClient_GetUser_Call{Call: _e.mock.On("GetUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *UserServiceClient_GetUser_Call) Run(run func(ctx context.Context, in *user_v1.GetUserRequest, opts ...grpc.CallOption)) *UserServiceClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user_v1.GetUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *UserServiceClient_GetUser_Call) Return(_a0 *user_v1.GetUserResponse, _a1 error) *UserServiceClient_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceClient_GetUser_Call) RunAndReturn(run func(context.Context, *user_v1.GetUserRequest, ...grpc.CallOption) (*user_v1.GetUserResponse, error)) *UserServiceClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) Register(ctx context.Context, in *user_v1.RegisterRequest, opts ...grpc.CallOption) (*user_v1.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *user_v1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user_v1.RegisterRequest, ...grpc.CallOption) (*user_v1.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user_v1.RegisterRequest, ...grpc.CallOption) *user_v1.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_v1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user_v1.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserServiceClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in *user_v1.RegisterRequest
//   - opts ...grpc.CallOption
func (_e *UserServiceClient_Expecter) Register(ctx interface{}, in interface{}, opts ...interface{}) *UserServiceClient_Register_Call {
	return &UserServiceClient_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *UserServiceClient_Register_Call) Run(run func(ctx context.Context, in *user_v1.RegisterRequest, opts ...grpc.CallOption)) *UserServiceClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*user_v1.RegisterRequest), variadicArgs...)
	})
	return _c
}

func (_c *UserServiceClient_Register_Call) Return(_a0 *user_v1.RegisterResponse, _a1 error) *UserServiceClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceClient_Register_Call) RunAndReturn(run func(context.Context, *user_v1.RegisterRequest, ...grpc.CallOption) (*user_v1.RegisterResponse, error)) *UserServiceClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserServiceClient creates a new instance of UserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceClient {
	mock := &UserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
