// Code generated for Alex Sokolov service
// © Alexey Sokolov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alexis871aa/microservices-rocket-factory/notification/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TelegramService is an autogenerated mock type for the TelegramService type
type TelegramService struct {
	mock.Mock
}

type TelegramService_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramService) EXPECT() *TelegramService_Expecter {
	return &TelegramService_Expecter{mock: &_m.Mock}
}

// SendOrderPaidNotification provides a mock function with given fields: ctx, event
func (_m *TelegramService) SendOrderPaidNotification(ctx context.Context, event model.OrderPaid) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPaidNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaid) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramService_SendOrderPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPaidNotification'
type TelegramService_SendOrderPaidNotification_Call struct {
	*mock.Call
}

// SendOrderPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaid
func (_e *TelegramService_Expecter) SendOrderPaidNotification(ctx interface{}, event interface{}) *TelegramService_SendOrderPaidNotification_Call {
	return &TelegramService_SendOrderPaidNotification_Call{Call: _e.mock.On("SendOrderPaidNotification", ctx, event)}
}

func (_c *TelegramService_SendOrderPaidNotification_Call) Run(run func(ctx context.Context, event model.OrderPaid)) *TelegramService_SendOrderPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaid))
	})
	return _c
}

func (_c *TelegramService_SendOrderPaidNotification_Call) Return(_a0 error) *TelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramService_SendOrderPaidNotification_Call) RunAndReturn(run func(context.Context, model.OrderPaid) error) *TelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendShipAssembledNotification provides a mock function with given fields: ctx, event
func (_m *TelegramService) SendShipAssembledNotification(ctx context.Context, event model.ShipAssembled) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendShipAssembledNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembled) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramService_SendShipAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendShipAssembledNotification'
type TelegramService_SendShipAssembledNotification_Call struct {
	*mock.Call
}

// SendShipAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembled
func (_e *TelegramService_Expecter) SendShipAssembledNotification(ctx interface{}, event interface{}) *TelegramService_SendShipAssembledNotification_Call {
	return &TelegramService_SendShipAssembledNotification_Call{Call: _e.mock.On("SendShipAssembledNotification", ctx, event)}
}

func (_c *TelegramService_SendShipAssembledNotification_Call) Run(run func(ctx context.Context, event model.ShipAssembled)) *TelegramService_SendShipAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembled))
	})
	return _c
}

func (_c *TelegramService_SendShipAssembledNotification_Call) Return(_a0 error) *TelegramService_SendShipAssembledNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramService_SendShipAssembledNotification_Call) RunAndReturn(run func(context.Context, model.ShipAssembled) error) *TelegramService_SendShipAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramService creates a new instance of TelegramService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramService {
	mock := &TelegramService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
