with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/alexis871aa/microservices-rocket-factory/inventory/internal/service:
    config:
      include-regex: ".*Service|.*Repository"

  github.com/alexis871aa/microservices-rocket-factory/inventory/internal/config:
    config:
      include-regex: ".*Config"

  github.com/alexis871aa/microservices-rocket-factory/order/internal/service:
    config:
      include-regex: ".*Service|.*Repository"

  github.com/alexis871aa/microservices-rocket-factory/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  github.com/alexis871aa/microservices-rocket-factory/order/internal/config:
    config:
      include-regex: ".*Config"

  github.com/alexis871aa/microservices-rocket-factory/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/alexis871aa/microservices-rocket-factory/payment/internal/config:
    config:
      include-regex: ".*Config"

  github.com/alexis871aa/microservices-rocket-factory/shared/pkg/proto/inventory/v1:
    config:
      include-regex: ".*ServiceClient"

  github.com/alexis871aa/microservices-rocket-factory/shared/pkg/proto/payment/v1:
    config:
      include-regex: ".*ServiceClient"

  github.com/alexis871aa/microservices-rocket-factory/assembly/internal/config:
    config:
      include-regex: ".*Config"

  github.com/alexis871aa/microservices-rocket-factory/assembly/internal/service:
    config:
      include-regex: ".*Service"

  github.com/alexis871aa/microservices-rocket-factory/notification/internal/config:
    config:
      include-regex: ".*Config"

  github.com/alexis871aa/microservices-rocket-factory/notification/internal/service:
    config:
      include-regex: ".*Service"
