// Code generated for Alex Sokolov service
// © Alexey Sokolov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AssemblyService is an autogenerated mock type for the AssemblyService type
type AssemblyService struct {
	mock.Mock
}

type AssemblyService_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyService) EXPECT() *AssemblyService_Expecter {
	return &AssemblyService_Expecter{mock: &_m.Mock}
}

// NewAssemblyService creates a new instance of AssemblyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyService {
	mock := &AssemblyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
