// Code generated for Alex Sokolov service
// © Alexey Sokolov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	auth_v1 "github.com/alexis871aa/microservices-rocket-factory/shared/pkg/proto/auth/v1"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AuthServiceClient is an autogenerated mock type for the AuthServiceClient type
type AuthServiceClient struct {
	mock.Mock
}

type AuthServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceClient) EXPECT() *AuthServiceClient_Expecter {
	return &AuthServiceClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) Login(ctx context.Context, in *auth_v1.LoginRequest, opts ...grpc.CallOption) (*auth_v1.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth_v1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) (*auth_v1.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) *auth_v1.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_v1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthServiceClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *auth_v1.LoginRequest
//   - opts ...grpc.CallOption
func (_e *AuthServiceClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *AuthServiceClient_Login_Call {
	return &AuthServiceClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *AuthServiceClient_Login_Call) Run(run func(ctx context.Context, in *auth_v1.LoginRequest, opts ...grpc.CallOption)) *AuthServiceClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*auth_v1.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *AuthServiceClient_Login_Call) Return(_a0 *auth_v1.LoginResponse, _a1 error) *AuthServiceClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthServiceClient_Login_Call) RunAndReturn(run func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) (*auth_v1.LoginResponse, error)) *AuthServiceClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) Whoami(ctx context.Context, in *auth_v1.WhoamiRequest, opts ...grpc.CallOption) (*auth_v1.WhoamiResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 *auth_v1.WhoamiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) (*auth_v1.WhoamiResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) *auth_v1.WhoamiResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_v1.WhoamiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthServiceClient_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type AuthServiceClient_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - in *auth_v1.WhoamiRequest
//   - opts ...grpc.CallOption
func (_e *AuthServiceClient_Expecter) Whoami(ctx interface{}, in interface{}, opts ...interface{}) *AuthServiceClient_Whoami_Call {
	return &AuthServiceClient_Whoami_Call{Call: _e.mock.On("Whoami",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *AuthServiceClient_Whoami_Call) Run(run func(ctx context.Context, in *auth_v1.WhoamiRequest, opts ...grpc.CallOption)) *AuthServiceClient_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*auth_v1.WhoamiRequest), variadicArgs...)
	})
	return _c
}

func (_c *AuthServiceClient_Whoami_Call) Return(_a0 *auth_v1.WhoamiResponse, _a1 error) *AuthServiceClient_Whoami_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthServiceClient_Whoami_Call) RunAndReturn(run func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) (*auth_v1.WhoamiResponse, error)) *AuthServiceClient_Whoami_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthServiceClient creates a new instance of AuthServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceClient {
	mock := &AuthServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
