// Code generated for Alex Sokolov service
// © Alexey Sokolov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InventoryGRPCClientConfig is an autogenerated mock type for the InventoryGRPCClientConfig type
type InventoryGRPCClientConfig struct {
	mock.Mock
}

type InventoryGRPCClientConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryGRPCClientConfig) EXPECT() *InventoryGRPCClientConfig_Expecter {
	return &InventoryGRPCClientConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *InventoryGRPCClientConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InventoryGRPCClientConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type InventoryGRPCClientConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *InventoryGRPCClientConfig_Expecter) Address() *InventoryGRPCClientConfig_Address_Call {
	return &InventoryGRPCClientConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *InventoryGRPCClientConfig_Address_Call) Run(run func()) *InventoryGRPCClientConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InventoryGRPCClientConfig_Address_Call) Return(_a0 string) *InventoryGRPCClientConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryGRPCClientConfig_Address_Call) RunAndReturn(run func() string) *InventoryGRPCClientConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryGRPCClientConfig creates a new instance of InventoryGRPCClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryGRPCClientConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryGRPCClientConfig {
	mock := &InventoryGRPCClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
