// Code generated for Alex Sokolov service
// © Alexey Sokolov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// OrderPaidConsumerConfig is an autogenerated mock type for the OrderPaidConsumerConfig type
type OrderPaidConsumerConfig struct {
	mock.Mock
}

type OrderPaidConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidConsumerConfig) EXPECT() *OrderPaidConsumerConfig_Expecter {
	return &OrderPaidConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *OrderPaidConsumerConfig) Config() *sarama.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if rf, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}

	return r0
}

// OrderPaidConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type OrderPaidConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *OrderPaidConsumerConfig_Expecter) Config() *OrderPaidConsumerConfig_Config_Call {
	return &OrderPaidConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *OrderPaidConsumerConfig_Config_Call) Run(run func()) *OrderPaidConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderPaidConsumerConfig_Config_Call) Return(_a0 *sarama.Config) *OrderPaidConsumerConfig_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *OrderPaidConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function with no fields
func (_m *OrderPaidConsumerConfig) GroupID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderPaidConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type OrderPaidConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *OrderPaidConsumerConfig_Expecter) GroupID() *OrderPaidConsumerConfig_GroupID_Call {
	return &OrderPaidConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *OrderPaidConsumerConfig_GroupID_Call) Run(run func()) *OrderPaidConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderPaidConsumerConfig_GroupID_Call) Return(_a0 string) *OrderPaidConsumerConfig_GroupID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *OrderPaidConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// TopicName provides a mock function with no fields
func (_m *OrderPaidConsumerConfig) TopicName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopicName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderPaidConsumerConfig_TopicName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopicName'
type OrderPaidConsumerConfig_TopicName_Call struct {
	*mock.Call
}

// TopicName is a helper method to define mock.On call
func (_e *OrderPaidConsumerConfig_Expecter) TopicName() *OrderPaidConsumerConfig_TopicName_Call {
	return &OrderPaidConsumerConfig_TopicName_Call{Call: _e.mock.On("TopicName")}
}

func (_c *OrderPaidConsumerConfig_TopicName_Call) Run(run func()) *OrderPaidConsumerConfig_TopicName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderPaidConsumerConfig_TopicName_Call) Return(_a0 string) *OrderPaidConsumerConfig_TopicName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidConsumerConfig_TopicName_Call) RunAndReturn(run func() string) *OrderPaidConsumerConfig_TopicName_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPaidConsumerConfig creates a new instance of OrderPaidConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidConsumerConfig {
	mock := &OrderPaidConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
